"""Configuration constants for the DigiShell backend."""

STATUS_POLL_INTERVAL = 5
CONNECTION_CHECK_INTERVAL = 50
POLL_SLEEP_INTERVAL = 0.1
CONSECUTIVE_FAILURE_THRESHOLD = 10
ERROR_RETRY_INTERVAL = 1
